export var spawnNames = [
  'Doppio',
  'Americano',
  'Espresso',
  'Espresso Lungo',
  'Ristretto',
  'Cortado',
  'Latte',
  'Cafe Au Lait',
  'Cappuccino',
  'Flat White',
  'Macchiato',
  'Espresso Con Panna',
  'Iced',
  'Cold Brew',
  'Frappe',
  'Frappuccino',
  'Drip',
  'Turkish',
  'French Press',
  'Pour Over',
  'Moka Pot',
  'Percolator',
  'Mocha',
  'Affogato',
  'Irish',
  'Caffe Correcto',
  'Liqueur',
];
